# Generated by Django 4.1.7 on 2023-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreMax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=50)),
                ('Work_description', models.TextField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
