# Generated by Django 4.1.7 on 2023-02-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreMax', '0002_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('Technical Course', 'Technical Course'), ('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=100)),
                ('school', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
