# Generated by Django 4.1.7 on 2023-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreMax', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('weblink', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField()),
            ],
        ),
    ]
