# Generated by Django 4.1.7 on 2023-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreMax', '0005_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='projects/')),
                ('ContentName', models.CharField(max_length=10)),
                ('ContentDesc', models.CharField(max_length=250)),
            ],
        ),
    ]
